[CmdletBinding()]
param([string]$HomeRoot='D:\lidiya',[string]$InstallRoot='D:\lidiya\0.dev_tools\home_bridge_v2',[switch]$UpdatePayloadMode)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$app='Lidiya Home Bridge';$ver='2.0.0-alpha.4';$seq=4;$start=Get-Date;$ts=$start.ToString('yyyyMMdd_HHmmss')
$rt=Join-Path $InstallRoot 'runtime';$lg=Join-Path $InstallRoot 'logs';$up=Join-Path $InstallRoot 'updater';$st=Join-Path $InstallRoot 'staging';$rels=Join-Path $InstallRoot 'releases';$rel=Join-Path $rels $ver;$cur=Join-Path $InstallRoot 'current.json';$report=Join-Path $lg ('ROUND4_AUDIT_'+$ts+'.json')
$base='https://raw.githubusercontent.com/KLRSACN/lidiya-laboratory/home-bridge-v2-round1/tools/home_bridge_v2';$manifest=$base+'/release_manifest.json'
function WJ($o,$p){$par=Split-Path -Parent $p;if($par -and -not(Test-Path -LiteralPath $par)){New-Item -ItemType Directory -Path $par -Force|Out-Null};$o|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $p -Encoding UTF8};function GH($p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Cloud{foreach($p in @('G:\我的雲端硬碟\Lidiya Memory','G:\My Drive\Lidiya Memory','H:\我的雲端硬碟\Lidiya Memory','H:\My Drive\Lidiya Memory')){if(Test-Path -LiteralPath $p -PathType Container){return $p}};return $null}
try{
 foreach($d in @($rt,$lg,$up,$st,$rels,$rel)){if(-not(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null}}
 $mods=@(
  [ordered]@{n='check_update.ps1';u=$base+'/updater/check_update.ps1';h='5542973ad01e101280e6a51c0119c8309ddbb0c704509728421b2006bfa5d8b6'},
  [ordered]@{n='rollback.ps1';u=$base+'/updater/rollback.ps1';h='a84b42744a34375efdac1c314fa9a4a04ed695d24c20e575c96b5d828e8e75e2'},
  [ordered]@{n='selftest.ps1';u=$base+'/updater/selftest.ps1';h='1b2def028ca1484a12c5f49013864f3c511d3253fbe61e8708fabbe81fed5df2'})
 [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
 foreach($m in $mods){$p=Join-Path $up $m.n;Invoke-WebRequest -UseBasicParsing -Uri $m.u -OutFile $p;if((GH $p)-ne $m.h){throw ('MODULE_SHA256_MISMATCH: '+$m.n)};Copy-Item -LiteralPath $p -Destination (Join-Path $rel $m.n) -Force}
 $payload=Join-Path $rel 'install_round4.ps1';Copy-Item -LiteralPath $MyInvocation.MyCommand.Path -Destination $payload -Force
 $files=@();foreach($n in @('install_round4.ps1','check_update.ps1','rollback.ps1','selftest.ps1')){$p=Join-Path $rel $n;$files+=[ordered]@{path=$n;sha256=GH $p;size_bytes=(Get-Item -LiteralPath $p).Length}}
 WJ ([ordered]@{schema_version=2;app=$app;version=$ver;sequence=$seq;created_at=(Get-Date).ToString('o');files=$files}) (Join-Path $rel 'release.json')
 & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $up 'selftest.ps1') -ReleaseDir $rel;if($LASTEXITCODE -ne 0){throw 'RELEASE_SELFTEST_FAILED'}
 if($UpdatePayloadMode){exit 0}
 $prog=Join-Path $rt 'ROUND_PROGRESS.json';if(-not(Test-Path -LiteralPath $prog -PathType Leaf)){throw 'ROUND3_PROGRESS_NOT_FOUND'};$r3=Get-Content -LiteralPath $prog -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$r3.status -ne 'ROUND3_PASS_CANDIDATE'){throw ('ROUND3_NOT_READY: '+$r3.status)}
 $old=if(Test-Path -LiteralPath $cur -PathType Leaf){Get-Content -LiteralPath $cur -Raw -Encoding UTF8|ConvertFrom-Json}else{$null};$pv=if($old){[string]$old.active_version}else{'2.0.0-alpha.3'};$pr=if($old){[string]$old.active_release}else{Join-Path $rels '2.0.0-alpha.3'};$ps=if($old -and $old.PSObject.Properties.Name -contains 'update_sequence'){[int]$old.update_sequence}else{3}
 WJ ([ordered]@{schema_version=2;app=$app;active_version=$ver;active_release=$rel;update_sequence=$seq;previous_version=$pv;previous_release=$pr;previous_sequence=$ps;status='ROUND4_CANDIDATE';updated_at=(Get-Date).ToString('o')}) $cur
 $cc=Join-Path $InstallRoot 'CHECK_HOME_BRIDGE_UPDATE.cmd';$rc=Join-Path $InstallRoot 'ROLLBACK_HOME_BRIDGE.cmd'
 ('@echo off'+[Environment]::NewLine+'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "'+(Join-Path $up 'check_update.ps1')+'" -ManifestUrl "'+$manifest+'"'+[Environment]::NewLine+'exit /b %ERRORLEVEL%')|Set-Content -LiteralPath $cc -Encoding ASCII
 ('@echo off'+[Environment]::NewLine+'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "'+(Join-Path $up 'rollback.ps1')+'"'+[Environment]::NewLine+'exit /b %ERRORLEVEL%')|Set-Content -LiteralPath $rc -Encoding ASCII
 $test=Join-Path $InstallRoot ('tests\round4_'+$ts);$tr1=Join-Path (Join-Path $test 'releases') 'test-1';foreach($d in @($test,$tr1)){if(-not(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null}}
 WJ ([ordered]@{schema_version=2;app=$app;active_version='test-1';active_release=$tr1;update_sequence=1;previous_version='none';previous_release=$tr1;previous_sequence=0;status='TEST_BASE';updated_at=(Get-Date).ToString('o')}) (Join-Path $test 'current.json');WJ ([ordered]@{schema_version=2;app=$app;version='test-1';sequence=1;files=@()}) (Join-Path $tr1 'release.json')
 $tp=Join-Path $test 'payload.ps1';@'
param([string]$InstallRoot,[switch]$UpdatePayloadMode)
$d=Join-Path (Join-Path $InstallRoot 'releases') 'test-2';if(-not(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Path $d -Force|Out-Null};'OK'|Set-Content -LiteralPath (Join-Path $d 'marker.txt') -Encoding UTF8;$h=(Get-FileHash -LiteralPath (Join-Path $d 'marker.txt') -Algorithm SHA256).Hash.ToLowerInvariant();([ordered]@{schema_version=2;app='Lidiya Home Bridge';version='test-2';sequence=2;files=@([ordered]@{path='marker.txt';sha256=$h})})|ConvertTo-Json -Depth 10|Set-Content -LiteralPath (Join-Path $d 'release.json') -Encoding UTF8;exit 0
'@|Set-Content -LiteralPath $tp -Encoding UTF8
 $tm=Join-Path $test 'manifest.json';WJ ([ordered]@{schema_version=2;version='test-2';sequence=2;payload_path=$tp;payload_sha256=GH $tp}) $tm
 & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $up 'check_update.ps1') -InstallRoot $test -ManifestPath $tm;$ue=$LASTEXITCODE;$ua=Get-Content -LiteralPath (Join-Path $test 'current.json') -Raw -Encoding UTF8|ConvertFrom-Json
 & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $up 'rollback.ps1') -InstallRoot $test;$re=$LASTEXITCODE;$ra=Get-Content -LiteralPath (Join-Path $test 'current.json') -Raw -Encoding UTF8|ConvertFrom-Json
 & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $up 'check_update.ps1') -InstallRoot $InstallRoot -ManifestUrl $manifest;$pe=$LASTEXITCODE
 $task='Lidiya Home Bridge Update Check';& schtasks.exe /Create /SC ONLOGON /TN $task /TR ('"'+$cc+'"') /F|Out-Null;$te=$LASTEXITCODE
 $checks=[ordered]@{round3_ready=([string]$r3.status -eq 'ROUND3_PASS_CANDIDATE');release_selftest_pass=$true;update_simulation_pass=($ue -eq 0 -and [string]$ua.active_version -eq 'test-2');rollback_simulation_pass=($re -eq 0 -and [string]$ra.active_version -eq 'test-1');production_manifest_check_pass=($pe -eq 0);check_cmd_exists=(Test-Path -LiteralPath $cc);rollback_cmd_exists=(Test-Path -LiteralPath $rc);scheduled_task_created=($te -eq 0)}
 $critical=$checks.round3_ready -and $checks.release_selftest_pass -and $checks.update_simulation_pass -and $checks.rollback_simulation_pass -and $checks.production_manifest_check_pass -and $checks.check_cmd_exists -and $checks.rollback_cmd_exists;$result=if($critical){'ROUND4_PASS_CANDIDATE'}else{'ROUND4_FAIL'}
 $rep=[ordered]@{schema_version=2;app=$app;version=$ver;sequence=$seq;result=$result;started_at=$start.ToString('o');completed_at=(Get-Date).ToString('o');computer_name=$env:COMPUTERNAME;checks=$checks;paths=[ordered]@{install=$InstallRoot;release=$rel;current=$cur;check_cmd=$cc;rollback_cmd=$rc;test_root=$test};integrity=[ordered]@{installer_sha256=GH $payload;release_json_sha256=GH (Join-Path $rel 'release.json');check_update_sha256=GH (Join-Path $up 'check_update.ps1');rollback_sha256=GH (Join-Path $up 'rollback.ps1');selftest_sha256=GH (Join-Path $up 'selftest.ps1')};scheduled_task=[ordered]@{name=$task;created=($te -eq 0);exit_code=$te;trigger='ONLOGON'};next_step='Online cloud readback and formal v2 baseline approval.';approval_state='CANDIDATE_NOT_FORMALLY_APPROVED'};WJ $rep $report
 WJ ([ordered]@{schema_version=2;project='Lidiya Home Bridge v2';current_round=4;status=$result;active_version=$ver;update_sequence=$seq;updated_at=(Get-Date).ToString('o');completed=@('closed-loop cloud readback','GitHub updater installed','SHA256 verification','controlled update simulation','controlled rollback simulation','CMD launchers');pending=@('online cloud readback','formal v2 approval');latest_report=$report;next_minimum_step='Read cloud HOME_BRIDGE_STATUS.json.'}) $prog
 $cl=Cloud;if($cl){$cr=Join-Path $cl 'Runtime';Copy-Item -LiteralPath $report -Destination (Join-Path $cr 'HOME_BRIDGE_STATUS.json') -Force;Copy-Item -LiteralPath $prog -Destination (Join-Path $cr 'ROUND_PROGRESS.json') -Force;Copy-Item -LiteralPath $report -Destination (Join-Path $cr ('ROUND4_AUDIT_'+$ts+'.json')) -Force;Copy-Item -LiteralPath (Join-Path $rel 'release.json') -Destination (Join-Path $cr 'HOME_BRIDGE_RELEASE.json') -Force}
 if(-not $critical){throw 'ROUND4_CRITICAL_VERIFICATION_FAILED'};Write-Host '';Write-Host 'ROUND4 PASS CANDIDATE' -ForegroundColor Green;Write-Host ('Local report: '+$report);if($cl){Write-Host ('Cloud report: '+(Join-Path (Join-Path $cl 'Runtime') 'HOME_BRIDGE_STATUS.json'))};Write-Host ('Update launcher: '+$cc);Write-Host ('Rollback launcher: '+$rc);if($te -ne 0){Write-Host 'Scheduled task not created; manual updater remains available.' -ForegroundColor Yellow};exit 0
}catch{$line=$_.InvocationInfo.ScriptLineNumber;$msg=$_.Exception.Message;try{$f=[ordered]@{schema_version=2;app=$app;version=$ver;result='ROUND4_FAIL';updated_at=(Get-Date).ToString('o');error_stage='ROUND4_INSTALL_TEST_OR_SCHEDULE';error_line=$line;error_id=$_.FullyQualifiedErrorId;error_category=$_.CategoryInfo.Category.ToString();error_message=$msg;result_report=$report};WJ $f (Join-Path $lg ('ROUND4_ERROR_'+$ts+'.json'));$cl=Cloud;if($cl){WJ $f (Join-Path (Join-Path $cl 'Runtime') 'HOME_BRIDGE_STATUS.json')}}catch{};Write-Host '';Write-Host ('ROUND4 FAIL: '+$msg) -ForegroundColor Red;Write-Host ('ERROR_LINE: '+$line) -ForegroundColor Red;exit 1}
